version: '2'

services:
  web:
    image: node:4
    entrypoint: ./bin/entrypoint.sh
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DB_HOST: mongo
      NODE_ENV: development
    ports:
      - 1337:1337
    depends_on:
      - mongo

  mongo:
    image: mongo
