version: '2'

services:
  web:
    build: .
    image: node:4
    entrypoint: ./bin/entrypoint.sh
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      DB_HOST: mongo
      DB_CONNECTION: mongoDocker
      NODE_ENV: production
    ports:
      - 1337:1337
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - 27018:27017

  redis:
    image: redis
    ports:
      - 6380:6379

  jmeter:
    build:
      context: .
      dockerfile: Dockerfile.jmeter
    entrypoint: /jmeter_entrypoint.sh
    environment:
      APP_HOST: web
