version: '2'

# cpu-period default to 1 second
# cpu-quota is in microseconds, so cpu-quota=1000000 is cpu 100%? 1 secd = 1000000 microsecds
# this resource configs expect 3 cpu and 3 GB ram (jmeter included)

services:
  web:
    build: .
    image: node:4
    cpu_quota: 1000000
    # cpuset: "0"
    mem_limit: 1024m
    memswap_limit: 1024m
    #mem_reservation: 1024m
    mem_swappiness: 0
    entrypoint: ./bin/entrypoint.sh
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      DB_HOST: mongo
      DB_CONNECTION: mongoDocker
      NODE_ENV: production
    ports:
      - 1337
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    cpu_quota: 750000
    cpuset: "1"
    mem_limit: 512m
    memswap_limit: 512m
    #mem_reservation: 512m
    mem_swappiness: 0
    ports:
      - 27018:27017

  redis:
    image: redis
    cpu_quota: 250000
    cpuset: "1"
    mem_limit: 512m
    memswap_limit: 512m
    #mem_reservation: 512m
    ports:
      - 6380:6379

  haproxy:
    image: dockercloud/haproxy
    ports:
      - "8080:80"
    links:
      - web
    # Linux config:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # MAC config:
    # environment:
    #   - DOCKER_TLS_VERIFY
    #   - DOCKER_HOST
    #   - DOCKER_CERT_PATH
    # volumes:
    #   - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH

  jmeter:
    build:
      context: .
      dockerfile: Dockerfile.jmeter
    cpu_quota: 1000000
    cpuset: "2"
    mem_limit: 1024m
    memswap_limit: 1024m
    #mem_reservation: 1024m
    mem_swappiness: 0
    entrypoint: /jmeter_entrypoint.sh
    environment:
      APP_HOST: web
